### ISSUE TITLE
Bug with referencing inside a definition list

### ISSUE THREAD

**Issue by adityam** [chdemko/pandoc-numbering#13]
Consider the following markdown file

```
Assumption #big

:   Big assumption

Lemma #

:   A random lemma

Lemma #

:   A random lemma

Now we derive a result which uses [Assumption #](#assumption:big).

Lemma #

:   Under [Assumption #](#assumption:big), we have ... 
```

Processing it using `pandoc --filter pandoc-numbering --to=markdown` gives
```
[**Assumption 1**]{#assumption:big .pandoc-numbering-text .assumption}

:   Big assumption

[**Lemma 1**]{#lemma:1 .pandoc-numbering-text .lemma}

:   A random lemma

[**Lemma 2**]{#lemma:2 .pandoc-numbering-text .lemma}

:   A random lemma

Now we derive a result which uses [Assumption 1](#assumption:big).

[**Lemma 3**]{#lemma:3 .pandoc-numbering-text .lemma}

:   Under [Assumption 3](#assumption:big), we have ...
```

Note that in Lemma 3, the "Assumption #" got translated to "Assumption 3" rather than "Assumption 1".

**Comment by aubertc** [comment]
I can reproduce your bug.
You can side-step it using the [short-cut notation](https://pandoc-numbering.readthedocs.io/en/latest/cite.html).
I'm assuming it really is a bug, and not a feature, since the "usual" way of referencing your assumption (cf. [this page](https://pandoc-numbering.readthedocs.io/en/latest/referencing.html)) still creates a bug.

```
Assumption #big

:   Big assumption

Lemma #

:   A random lemma

Lemma #

:   A random lemma

Now we derive a result which uses [%D %n](#assumption:big).

Lemma #

:   Under 

    - [Assumption #](#assumption:big), your example, does not work
    - [%D %n](#assumption:big), this solution should work, but does not either.
    - @assumption:big, this works.

```

produces:

<dl>
<dt><span id="assumption:big" class="pandoc-numbering-text assumption"><strong>Assumption 1</strong></span></dt>
<dd><p>Big assumption</p>
</dd>
<dt><span id="lemma:1" class="pandoc-numbering-text lemma"><strong>Lemma 1</strong></span></dt>
<dd><p>A random lemma</p>
</dd>
<dt><span id="lemma:2" class="pandoc-numbering-text lemma"><strong>Lemma 2</strong></span></dt>
<dd><p>A random lemma</p>
</dd>
</dl>
<p>Now we derive a result which uses <a href="#assumption:big">Assumption 1</a>.</p>
<dl>
<dt><span id="lemma:3" class="pandoc-numbering-text lemma"><strong>Lemma 3</strong></span></dt>
<dd><p>Under</p>
<ul>
<li><a href="#assumption:big">Assumption 3</a>: your example, does not work</li>
<li><a href="#assumption:big">Lemma 3</a>, this solution should work, but does not either.</li>
<li><a href="#assumption:big" title="Assumption 1"><span class="pandoc-numbering-link assumption">Assumption 1</span></a>, this works.</li>
</ul>
</dd>
</dl>

Note that if you are using [pandoc-citeproc](https://github.com/jgm/pandoc-citeproc) at the same time, [the order of the filters is important](https://github.com/chdemko/pandoc-numbering/issues/6).

**Comment by adityam** [comment]
Thanks! This workaround is sufficient for me.

**Comment by chdemko** [comment]
This is a bug. I have to look at it

**Comment by adityam** [comment]
Thanks a lot!
